# Generated by Django 6.0.4 on 2026-04-23 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order_rank'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('style_type', models.CharField(blank=True, max_length=100)),
                ('highlight_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('goal_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('movement_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('muscle_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('movement_category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['movement_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_compound', models.BooleanField(default=False)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps', models.PositiveSmallIntegerField(default=10)),
                ('instructions', models.TextField(blank=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='workouts.difficultylevel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.exerciseimage')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='workouts.movementtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('calories_per_100g', models.PositiveIntegerField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('ideal_for_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_foods', to='workouts.goaltype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_split', models.CharField(blank=True, max_length=50, null=True)),
                ('days_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('available_equipment', models.ManyToManyField(blank=True, to='workouts.equipment')),
                ('fitness_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.difficultylevel')),
                ('primary_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.goaltype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(blank=True, null=True)),
                ('day_name', models.CharField(blank=True, max_length=50, null=True)),
                ('num_exercises', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_workouts', to='workouts.difficultylevel')),
                ('target_muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_workouts', to='workouts.musclegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workouts', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.workoutprogram')),
            ],
            options={
                'ordering': ['program', 'day_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_equipment', to='workouts.equipment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_equipment', to='workouts.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exercise', 'equipment'), name='unique_exercise_equipment')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseGoalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sets', models.PositiveSmallIntegerField()),
                ('rep_low', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rep_high', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_profiles', to='workouts.exercise')),
                ('goal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profiles', to='workouts.goaltype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exercise', 'goal_type'), name='unique_exercise_goal_profile')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('stabilizer', 'Stabilizer')], default='primary', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscle_groups', to='workouts.exercise')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscle_groups', to='workouts.musclegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exercise', 'muscle_group', 'role'), name='unique_exercise_muscle_role')],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('supporting', 'Supporting'), ('stabilizer', 'Stabilizer'), ('synergist', 'Synergist')], default='supporting', max_length=20)),
                ('related_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='workouts.musclegroup')),
                ('source_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='workouts.musclegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_muscle_group', 'related_muscle_group', 'relationship_type'), name='unique_muscle_relationship')],
            },
        ),
        migrations.CreateModel(
            name='SavedWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_order', models.PositiveSmallIntegerField()),
                ('slot_type', models.CharField(choices=[('compound', 'Compound'), ('targeted', 'Targeted'), ('supporting', 'Supporting')], default='targeted', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workout_exercises', to='workouts.exercise')),
                ('saved_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.savedworkout')),
            ],
            options={
                'ordering': ['exercise_order'],
                'constraints': [models.UniqueConstraint(fields=('saved_workout', 'exercise_order'), name='unique_workout_exercise_order')],
            },
        ),
    ]
