# Generated by Django 4.2.30 on 2026-04-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order_rank'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_compound', models.BooleanField(default=False)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps', models.PositiveSmallIntegerField(default=10)),
                ('instructions', models.TextField(blank=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='workouts.difficultylevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('style_type', models.CharField(blank=True, max_length=100)),
                ('highlight_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('goal_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('movement_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('muscle_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('movement_category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['movement_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_exercises', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_workouts', to='workouts.difficultylevel')),
                ('target_muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_workouts', to='workouts.musclegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_order', models.PositiveSmallIntegerField()),
                ('slot_type', models.CharField(choices=[('compound', 'Compound'), ('targeted', 'Targeted'), ('supporting', 'Supporting')], default='targeted', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workout_exercises', to='workouts.exercise')),
                ('saved_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.savedworkout')),
            ],
            options={
                'ordering': ['exercise_order'],
            },
        ),
        migrations.AddField(
            model_name='savedworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workouts', to='workouts.user'),
        ),
        migrations.CreateModel(
            name='MuscleGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('supporting', 'Supporting'), ('stabilizer', 'Stabilizer'), ('synergist', 'Synergist')], default='supporting', max_length=20)),
                ('related_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='workouts.musclegroup')),
                ('source_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='workouts.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('stabilizer', 'Stabilizer')], default='primary', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscle_groups', to='workouts.exercise')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscle_groups', to='workouts.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGoalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sets', models.PositiveSmallIntegerField()),
                ('rep_low', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rep_high', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_profiles', to='workouts.exercise')),
                ('goal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profiles', to='workouts.goaltype')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_equipment', to='workouts.equipment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_equipment', to='workouts.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.exerciseimage'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='workouts.movementtype'),
        ),
        migrations.AddConstraint(
            model_name='savedworkoutexercise',
            constraint=models.UniqueConstraint(fields=('saved_workout', 'exercise_order'), name='unique_workout_exercise_order'),
        ),
        migrations.AddConstraint(
            model_name='musclegrouprelationship',
            constraint=models.UniqueConstraint(fields=('source_muscle_group', 'related_muscle_group', 'relationship_type'), name='unique_muscle_relationship'),
        ),
        migrations.AddConstraint(
            model_name='exercisemusclegroup',
            constraint=models.UniqueConstraint(fields=('exercise', 'muscle_group', 'role'), name='unique_exercise_muscle_role'),
        ),
        migrations.AddConstraint(
            model_name='exercisegoalprofile',
            constraint=models.UniqueConstraint(fields=('exercise', 'goal_type'), name='unique_exercise_goal_profile'),
        ),
        migrations.AddConstraint(
            model_name='exerciseequipment',
            constraint=models.UniqueConstraint(fields=('exercise', 'equipment'), name='unique_exercise_equipment'),
        ),
    ]
